# services:
#   db:
#     image: postgres:15
#     container_name: postgres_db
#     restart: always
#     env_file:
#       - .env
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   web:
#     build: .
#     container_name: django_app
#     restart: always
#     env_file:
#       - .env
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

# volumes:
#   postgres_data:



services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
