server {
    listen 80;
    server_name systemnotif.com www.systemnotif.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name systemnotif.com www.systemnotif.com;

    ssl_certificate /certs/live/systemnotif.com/fullchain.pem;
    ssl_certificate_key /certs/live/systemnotif.com/privkey.pem;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
