# Generated by Django 5.2.8 on 2025-11-12 13:41

import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', notifications.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='priority_db',
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='time_window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='time_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
