# Generated by Django 5.2.8 on 2025-11-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_user_managers_remove_user_priority_db_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="priority_db",
            field=models.CharField(blank=True, default="faible", max_length=10),
        ),
        migrations.AlterField(
            model_name="notification",
            name="priority",
            field=models.CharField(default="faible", max_length=10),
        ),
    ]
